### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jinjun1994** [MengWoods/pdf-compressor#1]
File "D:\jinjun\pdf-compressor\utils\pdfUtils.py", line 34, in ocrAndSaveTxt
    f.write(page.extract_text())
UnicodeEncodeError: 'gbk' codec can't encode character '\ufb00' in position 81: illegal multibyte sequence

**Comment by MengWoods** [comment]
Hi, could you link the PDF for my testing? Thanks.

**Comment by MengWoods** [comment]
@jinjun1994 Hi, could you link the PDF for my testing? Thanks
